# Generated by Django 5.0.3 on 2024-03-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_message_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friends',
            new_name='Chats',
        ),
    ]
